language: python

python:
  - "2.7"

install:
  - "pip install --upgrade setuptools pip"
  - "pip install -U -r requirements.txt"
  - "pip install -U -r dev-requirements.txt"

script:
  - "py.test"

after_success:
  - "coveralls"

notifications:
  email: false
