"""Create db tables

Revision ID: b9308d306405
Revises: c36480cd22db
Create Date: 2021-02-05 15:18:06.547834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9308d306405'
down_revision = 'c36480cd22db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bibcode', sa.String(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('eprint', sa.Boolean(), nullable=True),
    sa.Column('figures', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('modtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphics_bibcode'), 'graphics', ['bibcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graphics_bibcode'), table_name='graphics')
    op.drop_table('graphics')
    # ### end Alembic commands ###
