"""Add baseurl column

Revision ID: de7cb4b6482f
Revises: 80ecdb88cee2
Create Date: 2021-02-09 12:36:02.897204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7cb4b6482f'
down_revision = '80ecdb88cee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphics', sa.Column('baseurl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graphics', 'baseurl')
    # ### end Alembic commands ###
