"""empty message

Revision ID: 437251c0dc94
Revises: None
Create Date: 2015-05-14 12:56:24.832618

"""

# revision identifiers, used by Alembic.
revision = '437251c0dc94'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
